# Date: 31 July 2019
# Task: 1. Import and clean datasets of river flow, 15 min river level, daily river level, power 
#       generation
#       2. Exploratory data analysis of flow data, power generation data, and combination
#          of these two datasets

# Import data
flow <- read.csv('/Users/lilu/Desktop/dissertation 2/data/don_parkhill_flow.csv')
fifmin <-read.csv('/Users/lilu/Desktop/dissertation 2/data/don_parkhill_level_15min.csv')
level <- read.csv('/Users/lilu/Desktop/dissertation 2/data/don_parkhill_level.csv')
generation <- read.csv('/Users/lilu/Desktop/dissertation 2/data/generation.csv')

########################## Generation Data from ACE
# Delete the rows of null values of t1_avg_power in power generation data 
new_generation <- generation[generation$t1_avg_power != 0, ]

# Aggregate the power generation of the same date
new_generation$time <- NULL
agg_gen <- aggregate(. ~date, data=new_generation, mean)

# Change the date format from "%d/%m/%Y" to "%Y-%m-%d"
agg_gen$date <- format(as.Date(agg_gen$date, format = "%d/%m/%Y"), "%Y-%m-%d")
agg_gen
gen11 <- agg_gen
gen11$MonthN <- as.numeric(format(as.Date(gen11$date),"%m")) # Month's number
gen11$YearN <- as.numeric(format(as.Date(gen11$date),"%Y"))
gen11$Month  <- months(as.Date(gen11$date), abbreviate=TRUE) # Month's abbr.

# Load packages
library(dplyr)
library(ggplot2)

# Plot meter_power against month
Ref_Gen2_meter <- gen11 %>%
  group_by(MonthN,YearN, Month) %>%
  summarize(meter_power = mean(meter_power)) %>%
  ungroup() %>%
  # Convert the Month column to factor variable with levels from Jan to Dec
  # Convert the YearN column to factor
  mutate(Month = factor(Month, levels = unique(Month)),
         YearN = as.factor(YearN))

z <- ggplot(data = Ref_Gen2_meter, 
            aes(x = Month, y = meter_power, group = YearN, colour = YearN)) + 
  geom_line() 


# Plot average_power against month
Ref_Gen2 <- gen11 %>%
  group_by(MonthN, YearN, Month) %>%
  summarize(average_power = mean(t1_avg_power)) %>%
  ungroup() %>%
  # Convert the Month column to factor variable with levels from Jan to Dec
  # Convert the YearN column to factor
  mutate(Month = factor(Month, levels = unique(Month)),
         YearN = as.factor(YearN))

kk <- ggplot(data = Ref_Gen2, 
             aes(x = Month, y = average_power, group = YearN, colour = YearN)) + 
  geom_line() 

# Plot AOD_Downstream against month
Ref_Gen2_ds <- gen11 %>%
  group_by(MonthN, YearN, Month) %>%
  summarize(AOD_Downstream = mean(ds_lvl)) %>%
  ungroup() %>%
  # Convert the Month column to factor variable with levels from Jan to Dec
  # Convert the YearN column to factor
  mutate(Month = factor(Month, levels = unique(Month)),
         YearN = as.factor(YearN))

zz <- ggplot(data = Ref_Gen2_ds, 
             aes(x = Month, y = AOD_Downstream, group = YearN, colour = YearN)) + 
  geom_line() 

# Plot Flow_through_the_Turbine against month
Ref_Gen2_flow <- gen11 %>%
  group_by(MonthN, YearN, Month) %>%
  summarize(Flow_through_the_Turbine= mean(t1_flow)) %>%
  ungroup() %>%
  # Convert the Month column to factor variable with levels from Jan to Dec
  # Convert the YearN column to factor
  mutate(Month = factor(Month, levels = unique(Month)),
         YearN = as.factor(YearN))

zzz <- ggplot(data = Ref_Gen2_flow, 
              aes(x = Month, y = Flow_through_the_Turbine, group = YearN, colour = YearN)) + 
  geom_line() 

# Load the package
library(gridExtra)

# Combine the above graphs together
grid.arrange(z,kk,zz,zzz,
             ncol = 2)

# load the package
install.packages("chron")
library("chron")
library(ggplot2)


# Classify data in different time period such as morning, evening and night.
# Note: 5-11 the morning, 11-16 the afternoon, 16-19 evening, and anything beyond 
#       that and up until 5 night
new_generation2 <- generation[generation$t1_avg_power != 0, ]
tod <- cut(chron::times(new_generation2$time) , breaks = (1/24) * c(0,5,11,16,19,24))
time_data <- c("night","morning","afternoon","evening","night")[as.numeric(tod)]
comb_time_gen <- cbind(new_generation,time_data)
theme_set(theme_classic())

# Plot the box plot of amount of power entering the grid
f <- ggplot(comb_time_gen, aes(time_data, meter_power))
ff <- f + geom_boxplot(varwidth=T, fill="plum") + 
  labs(subtitle="Amount of Power Entering the Grid by Class of time",
       x="Class of Time",
       y="Amount of Power entering the Grid")

# Plot the box plot of power output from the turbine
# Note: we have removed the outlier
g <- ggplot(comb_time_gen, aes(time_data, t1_avg_power))
gg <- g + geom_boxplot(varwidth=T, fill="plum",outlier.shape = NA) + 
  labs(subtitle="Average Power Generated by Class of time",
       x="Class of Time",
       y="Power Output from the Turbine")

# Plot the box plot of measured AOD downstream
# Note: we have removed the outliers
w <- ggplot(comb_time_gen, aes(time_data, ds_lvl))
ww <- w + geom_boxplot(varwidth=T, fill="plum",outlier.shape = NA) + 
  labs(subtitle="Measured AOD Downstream by Class of time",
       x="Class of Time",
       y="Measured AOD Downstream")

# Plot the box plot of measured flow through the turbine
m <-ggplot(comb_time_gen, aes(time_data, t1_flow))
mm <- m + geom_boxplot(varwidth=T, fill="plum") + 
  labs(subtitle="Measured Flow through the Turbine by Class of time",
       x="Class of Time",
       y="Flow through the Turbine")

# Combine the above graphs together
library(gridExtra)
grid.arrange(ff,gg,ww,mm,
             ncol = 2)

########################## River data from SEPA
# Load the package
install.packages("hydroTSM")
library("hydroTSM")

# Divide flow by season
flow$date <- as.Date(flow$date)
seasons <- time2season(flow$date, out.fmt="seasons")
comb_seas <- cbind(flow, seasons)
comb_seas$seasons <- factor(comb_seas$seasons,
                            levels = c('spring','summer','autumm','winter'),ordered = TRUE)

# Load the package
library(ggplot2)
theme_set(theme_classic())

# Plot the box plot of flow by season
oo <- ggplot(comb_seas, aes(seasons, flow))
oo + geom_boxplot(varwidth=T, fill="plum",outlier.shape = NA) + 
  labs(title="Box plot", 
       subtitle="Flow by Class of Season",
       x="Class of Season",
       y="Flow") +
  scale_y_continuous(limits = c(0,60))

# import again the flow data and specify information of month and year to the dataset
flow11 <- read.csv('/Users/lilu/Desktop/dissertation 2/data/don_parkhill_flow.csv')
flow11$MonthN <- as.numeric(format(as.Date(flow11$date),"%m")) # Month's number
flow11$YearN <- as.numeric(format(as.Date(flow11$date),"%Y"))
flow11$Month  <- months(as.Date(flow11$date), abbreviate=TRUE) # Month's abbr.

# load the package
library(dplyr)

# Specify the month of each flow data
Ref_Data2 <- flow11 %>%
  group_by(MonthN, YearN, Month) %>%
  summarize(flow = mean(flow)) %>%
  ungroup() %>%
  # Convert the Month column to factor variable with levels from Jan to Dec
  # Convert the YearN column to factor
  mutate(Month = factor(Month, levels = unique(Month)),
         YearN = as.factor(YearN))

# Plot the flow data in 50 years against month
g <- ggplot(data = Ref_Data2, 
            aes(x = Month, y = flow, group = YearN, colour = YearN)) 
g +geom_line()
g + geom_smooth(se = F)

# Specify the flow data in 1975
g + geom_line(aes(group = YearN), color = "black", alpha = 0.1) +
  geom_line(data = function(x) filter(x, YearN == 1975), size = 1)

# Specify the flow data in 1985
g + geom_line(aes(group = YearN), color = "black", alpha = 0.1) +
  geom_line(data = function(x) filter(x, YearN == 1985), size = 1)

# Specify the flow data in 1995
g + geom_line(aes(group = YearN), color = "black", alpha = 0.1) +
  geom_line(data = function(x) filter(x, YearN == 1995), size = 1)

# Specify the flow data in 2005
g + geom_line(aes(group = YearN), color = "black", alpha = 0.1) +
  geom_line(data = function(x) filter(x, YearN == 2005), size = 1)

# Specify the flow data in 2015
g + geom_line(aes(group = YearN), color = "black", alpha = 0.1) +
  geom_line(data = function(x) filter(x, YearN == 2015), size = 1)
#By putting these 5 plots next to each other, this allowed us to see if there is a 
#drastic change in trend of the flow data throughout these 50 years



# Barplot of avearge flow per month
agg_flow_month <- aggregate(. ~Month, data=flow11, mean)
rownames(agg_flow_month) <- agg_flow_month$Month
new_agg_month <-agg_flow_month[c("Jan", "Feb", "Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")
                               ,]
barplot(new_agg_month$flow,
        names.arg=new_agg_month$Month,
        xlab = "Month", ylab = "avearge flow",
        main = "Average Flow Per Month"
)


# Import and clean the 15 min data
fifmin_new <-read.csv('/Users/lilu/Desktop/dissertation 2/data/15min.csv')
fifteen <- aggregate(level~date,data=fifmin_new,mean)
fifteen$date <- as.Date(fifteen$date, format = "%Y-%m-%d")

# Find the 15 min level data after 2017-03-31
want <- fifteen[fifteen$date >= as.Date("2017-03-31"),]

# Find the daily level data before 2019-07-01
level[,2] <- NULL 
level[,3] <-NULL
class(level$date)
level$date <- as.Date(level$date, format = "%Y-%m-%d")
want2 <- level[level$date <= as.Date("2019-07-01"),]

# Plot level against date of both daily data and 15 min data
plot(want$date,want$level)
plot(want2$date,want2$avg_level)

# Plot level from 15 min data
www<-ggplot(want, aes(x=want$date, y= want$level)) + 
  geom_point(color="blue")+
  geom_smooth(linetype="dashed",color="red")+
  labs(title="Level from 15min Data",
       x="Date", y = "Level")

# Plot level from daily data
wwww<-ggplot(want2, aes(x=want2$date, y= want2$avg_level)) + 
  geom_point(color="blue")+
  geom_smooth(linetype="dashed",color="red")+
  labs(title="Avearge Level from Daily Data",
       x="Date", y = "Average Level")

# Combine the above two pictures
library(gridExtra)
grid.arrange(www,wwww,
             ncol = 2)

####################### Combination of flow and power generation data
# Load the package
library(data.table)
setDT(agg_gen); setDT(flow)

# Merge power generation and flow data
agg_gen$date <- as.Date(agg_gen$date)
merge_gen_flow  <- merge(agg_gen,flow,by="date",allow.cartesian=T)
dim(merge_gen_flow)

# Plot river flow vs power output from the turbine
s <- ggplot(merge_gen_flow, aes(x=merge_gen_flow$flow, y= merge_gen_flow$t1_avg_power)) + 
  geom_point(color="blue")+
  geom_smooth(linetype="dashed",color="red")+
  labs(title="River Flow vs Power Output from the Turbine",
       x="River Flow", y = "Power Output from the Turbine")

# Plot river flow vs AOD downstream of the turbine
ss <- ggplot(merge_gen_flow, aes(x=merge_gen_flow$flow, y= merge_gen_flow$ds_lvl)) + 
  geom_point(color="blue")+
  geom_smooth(linetype="dashed",color="red")+
  labs(title="River Flow vs AOD Downstream of the Turbine",
       x="River Flow", y = "AOD Downstream of the Turbine")

# Plot river flow vs speed of the turbine
sss <- ggplot(merge_gen_flow, aes(x=merge_gen_flow$flow,
                                  y= merge_gen_flow$t1_speed
)) + 
  geom_point(color="blue")+
  geom_smooth(linetype="dashed",color="red")+
  labs(title="River Flow vs Speed of the Turbine",
       x="River Flow", y = "Speed of the Turbine") +
  coord_cartesian(ylim = c(0, 20))

# Plot river flow vs flow through the turbine
ssss <- ggplot(merge_gen_flow, aes(x=merge_gen_flow$flow, y= merge_gen_flow$t1_flow)) + 
  geom_point(color="blue")+
  geom_smooth(linetype="dashed",color="red")+
  labs(title="River Flow vs Flow through the Turbine",
       x="River Flow", y = "Flow through the Turbine")

# Combine the above pictures
library(gridExtra)
grid.arrange(s,ss,sss,ssss,
             ncol = 2)

##################### Find correlation between SEPA and ACE dataset
# Clean the datasets
new_merg <- merge_gen_flow_level[,c(2,3,4,5,6,7,8,10,11,12)]
colnames(new_merg)
names(new_merg)[names(new_merg) == "meter_power"] <- "Amount of Power Entering the Grid"
names(new_merg)[names(new_merg) == "t1_avg_power"] <- "Power Output"
names(new_merg)[names(new_merg) == "us_lvl"] <- "AOD Upstream"
names(new_merg)[names(new_merg) == "ds_lvl"] <- "AOD Downstream"
names(new_merg)[names(new_merg) == "t1_speed"] <- "Speed"
names(new_merg)[names(new_merg) == "t1_flow"] <- "Flow through the Turbine"
names(new_merg)[names(new_merg) == "flow"] <- "River Flow"
names(new_merg)[names(new_merg) == "min_level"] <- "Lowest River Level"
names(new_merg)[names(new_merg) == "avg_level"] <- "Average River Level"
names(new_merg)[names(new_merg) == "max_level"] <- "Highest River Level"

# Get the correlation and round the values to 2 decimals
cor(new_merg)
round(cor(new_merg),2)

# Load the package and get heatmap of the correlation
library(ggcorrplot)
ggcorrplot(round(cor(new_merg),2), hc.order = FALSE, type = "lower",
           lab = TRUE)